// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package org.mapstruct.ap.protobuf.test._target;

/**
 * Protobuf type {@code crenjoy.protobuf.BasicTestMessageMap}
 */
public final class BasicTestMessageMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.BasicTestMessageMap)
    BasicTestMessageMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BasicTestMessageMap.newBuilder() to construct.
  private BasicTestMessageMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BasicTestMessageMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BasicTestMessageMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BasicTestMessageMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              testStrMap_ = com.google.protobuf.MapField.newMapField(
                  TestStrMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            testStrMap__ = input.readMessage(
                TestStrMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            testStrMap_.getMutableMap().put(
                testStrMap__.getKey(), testStrMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetTestStrMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.class, org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.Builder.class);
  }

  public static final int TEST_STR_MAP_FIELD_NUMBER = 1;
  private static final class TestStrMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> testStrMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTestStrMap() {
    if (testStrMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TestStrMapDefaultEntryHolder.defaultEntry);
    }
    return testStrMap_;
  }

  public int getTestStrMapCount() {
    return internalGetTestStrMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */

  @java.lang.Override
  public boolean containsTestStrMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTestStrMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTestStrMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTestStrMap() {
    return getTestStrMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getTestStrMapMap() {
    return internalGetTestStrMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getTestStrMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTestStrMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getTestStrMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTestStrMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTestStrMap(),
        TestStrMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTestStrMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      testStrMap__ = TestStrMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, testStrMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap)) {
      return super.equals(obj);
    }
    org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap other = (org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap) obj;

    if (!internalGetTestStrMap().equals(
        other.internalGetTestStrMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetTestStrMap().getMap().isEmpty()) {
      hash = (37 * hash) + TEST_STR_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTestStrMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crenjoy.protobuf.BasicTestMessageMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.BasicTestMessageMap)
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTestStrMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableTestStrMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.class, org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.Builder.class);
    }

    // Construct using org.mapstruct.ap.protobuf.test.target.BasicTestMessageMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableTestStrMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap getDefaultInstanceForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.getDefaultInstance();
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap build() {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap buildPartial() {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap result = new org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap(this);
      int from_bitField0_ = bitField0_;
      result.testStrMap_ = internalGetTestStrMap();
      result.testStrMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap) {
        return mergeFrom((org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap other) {
      if (other == org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap.getDefaultInstance()) return this;
      internalGetMutableTestStrMap().mergeFrom(
          other.internalGetTestStrMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> testStrMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTestStrMap() {
      if (testStrMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TestStrMapDefaultEntryHolder.defaultEntry);
      }
      return testStrMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTestStrMap() {
      onChanged();;
      if (testStrMap_ == null) {
        testStrMap_ = com.google.protobuf.MapField.newMapField(
            TestStrMapDefaultEntryHolder.defaultEntry);
      }
      if (!testStrMap_.isMutable()) {
        testStrMap_ = testStrMap_.copy();
      }
      return testStrMap_;
    }

    public int getTestStrMapCount() {
      return internalGetTestStrMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */

    @java.lang.Override
    public boolean containsTestStrMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTestStrMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTestStrMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTestStrMap() {
      return getTestStrMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTestStrMapMap() {
      return internalGetTestStrMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getTestStrMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTestStrMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getTestStrMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTestStrMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTestStrMap() {
      internalGetMutableTestStrMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */

    public Builder removeTestStrMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTestStrMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTestStrMap() {
      return internalGetMutableTestStrMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */
    public Builder putTestStrMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableTestStrMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; test_str_map = 1;</code>
     */

    public Builder putAllTestStrMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTestStrMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.BasicTestMessageMap)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.BasicTestMessageMap)
  private static final org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap();
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BasicTestMessageMap>
      PARSER = new com.google.protobuf.AbstractParser<BasicTestMessageMap>() {
    @java.lang.Override
    public BasicTestMessageMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BasicTestMessageMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BasicTestMessageMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BasicTestMessageMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mapstruct.ap.protobuf.test._target.BasicTestMessageMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

