/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package org.mapstruct.ap.protobuf.test._target;

public interface BasicTestIntMessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.BasicTestIntMessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @return A list containing the testIntList.
   */
  java.util.List<java.lang.Integer> getTestIntListList();
  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @return The count of testIntList.
   */
  int getTestIntListCount();
  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @param index The index of the element to return.
   * @return The testIntList at the given index.
   */
  int getTestIntList(int index);
}
