/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package org.mapstruct.ap.protobuf.test._target;

/**
 * Protobuf type {@code crenjoy.protobuf.BasicTestMessageList}
 */
public final class BasicTestMessageList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.BasicTestMessageList)
    BasicTestMessageListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BasicTestMessageList.newBuilder() to construct.
  private BasicTestMessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BasicTestMessageList() {
    testStrList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BasicTestMessageList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BasicTestMessageList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              testStrList_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            testStrList_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        testStrList_ = testStrList_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.class, org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.Builder.class);
  }

  public static final int TEST_STR_LIST_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList testStrList_;
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @return A list containing the testStrList.
   */
  public com.google.protobuf.ProtocolStringList
      getTestStrListList() {
    return testStrList_;
  }
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @return The count of testStrList.
   */
  public int getTestStrListCount() {
    return testStrList_.size();
  }
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @param index The index of the element to return.
   * @return The testStrList at the given index.
   */
  public java.lang.String getTestStrList(int index) {
    return testStrList_.get(index);
  }
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the testStrList at the given index.
   */
  public com.google.protobuf.ByteString
      getTestStrListBytes(int index) {
    return testStrList_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < testStrList_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testStrList_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < testStrList_.size(); i++) {
        dataSize += computeStringSizeNoTag(testStrList_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTestStrListList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mapstruct.ap.protobuf.test._target.BasicTestMessageList)) {
      return super.equals(obj);
    }
    org.mapstruct.ap.protobuf.test._target.BasicTestMessageList other = (org.mapstruct.ap.protobuf.test._target.BasicTestMessageList) obj;

    if (!getTestStrListList()
        .equals(other.getTestStrListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTestStrListCount() > 0) {
      hash = (37 * hash) + TEST_STR_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getTestStrListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mapstruct.ap.protobuf.test._target.BasicTestMessageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crenjoy.protobuf.BasicTestMessageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.BasicTestMessageList)
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.class, org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.Builder.class);
    }

    // Construct using org.mapstruct.ap.protobuf.test.target.BasicTestMessageList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testStrList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageList getDefaultInstanceForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.getDefaultInstance();
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageList build() {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestMessageList buildPartial() {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageList result = new org.mapstruct.ap.protobuf.test._target.BasicTestMessageList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        testStrList_ = testStrList_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.testStrList_ = testStrList_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mapstruct.ap.protobuf.test._target.BasicTestMessageList) {
        return mergeFrom((org.mapstruct.ap.protobuf.test._target.BasicTestMessageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mapstruct.ap.protobuf.test._target.BasicTestMessageList other) {
      if (other == org.mapstruct.ap.protobuf.test._target.BasicTestMessageList.getDefaultInstance()) return this;
      if (!other.testStrList_.isEmpty()) {
        if (testStrList_.isEmpty()) {
          testStrList_ = other.testStrList_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTestStrListIsMutable();
          testStrList_.addAll(other.testStrList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mapstruct.ap.protobuf.test._target.BasicTestMessageList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mapstruct.ap.protobuf.test._target.BasicTestMessageList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList testStrList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTestStrListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        testStrList_ = new com.google.protobuf.LazyStringArrayList(testStrList_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @return A list containing the testStrList.
     */
    public com.google.protobuf.ProtocolStringList
        getTestStrListList() {
      return testStrList_.getUnmodifiableView();
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @return The count of testStrList.
     */
    public int getTestStrListCount() {
      return testStrList_.size();
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param index The index of the element to return.
     * @return The testStrList at the given index.
     */
    public java.lang.String getTestStrList(int index) {
      return testStrList_.get(index);
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the testStrList at the given index.
     */
    public com.google.protobuf.ByteString
        getTestStrListBytes(int index) {
      return testStrList_.getByteString(index);
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param index The index to set the value at.
     * @param value The testStrList to set.
     * @return This builder for chaining.
     */
    public Builder setTestStrList(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTestStrListIsMutable();
      testStrList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param value The testStrList to add.
     * @return This builder for chaining.
     */
    public Builder addTestStrList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTestStrListIsMutable();
      testStrList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param values The testStrList to add.
     * @return This builder for chaining.
     */
    public Builder addAllTestStrList(
        java.lang.Iterable<java.lang.String> values) {
      ensureTestStrListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, testStrList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestStrList() {
      testStrList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string test_str_list = 1;</code>
     * @param value The bytes of the testStrList to add.
     * @return This builder for chaining.
     */
    public Builder addTestStrListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTestStrListIsMutable();
      testStrList_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.BasicTestMessageList)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.BasicTestMessageList)
  private static final org.mapstruct.ap.protobuf.test._target.BasicTestMessageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mapstruct.ap.protobuf.test._target.BasicTestMessageList();
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestMessageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BasicTestMessageList>
      PARSER = new com.google.protobuf.AbstractParser<BasicTestMessageList>() {
    @java.lang.Override
    public BasicTestMessageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BasicTestMessageList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BasicTestMessageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BasicTestMessageList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mapstruct.ap.protobuf.test._target.BasicTestMessageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

