/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package org.mapstruct.ap.protobuf.test._target;

/**
 * Protobuf type {@code crenjoy.protobuf.BasicTestIntMessageList}
 */
public final class BasicTestIntMessageList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.BasicTestIntMessageList)
    BasicTestIntMessageListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BasicTestIntMessageList.newBuilder() to construct.
  private BasicTestIntMessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BasicTestIntMessageList() {
    testIntList_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BasicTestIntMessageList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BasicTestIntMessageList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              testIntList_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            testIntList_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              testIntList_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              testIntList_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        testIntList_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestIntMessageList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestIntMessageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.class, org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.Builder.class);
  }

  public static final int TEST_INT_LIST_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList testIntList_;
  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @return A list containing the testIntList.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getTestIntListList() {
    return testIntList_;
  }
  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @return The count of testIntList.
   */
  public int getTestIntListCount() {
    return testIntList_.size();
  }
  /**
   * <code>repeated int32 test_int_list = 1;</code>
   * @param index The index of the element to return.
   * @return The testIntList at the given index.
   */
  public int getTestIntList(int index) {
    return testIntList_.getInt(index);
  }
  private int testIntListMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getTestIntListList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(testIntListMemoizedSerializedSize);
    }
    for (int i = 0; i < testIntList_.size(); i++) {
      output.writeInt32NoTag(testIntList_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < testIntList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(testIntList_.getInt(i));
      }
      size += dataSize;
      if (!getTestIntListList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      testIntListMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList)) {
      return super.equals(obj);
    }
    org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList other = (org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList) obj;

    if (!getTestIntListList()
        .equals(other.getTestIntListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTestIntListCount() > 0) {
      hash = (37 * hash) + TEST_INT_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getTestIntListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crenjoy.protobuf.BasicTestIntMessageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.BasicTestIntMessageList)
      org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestIntMessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestIntMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.class, org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.Builder.class);
    }

    // Construct using org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testIntList_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestMessageProto.internal_static_crenjoy_protobuf_BasicTestIntMessageList_descriptor;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList getDefaultInstanceForType() {
      return org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.getDefaultInstance();
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList build() {
      org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList buildPartial() {
      org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList result = new org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        testIntList_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.testIntList_ = testIntList_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList) {
        return mergeFrom((org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList other) {
      if (other == org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList.getDefaultInstance()) return this;
      if (!other.testIntList_.isEmpty()) {
        if (testIntList_.isEmpty()) {
          testIntList_ = other.testIntList_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTestIntListIsMutable();
          testIntList_.addAll(other.testIntList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList testIntList_ = emptyIntList();
    private void ensureTestIntListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        testIntList_ = mutableCopy(testIntList_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @return A list containing the testIntList.
     */
    public java.util.List<java.lang.Integer>
        getTestIntListList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(testIntList_) : testIntList_;
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @return The count of testIntList.
     */
    public int getTestIntListCount() {
      return testIntList_.size();
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @param index The index of the element to return.
     * @return The testIntList at the given index.
     */
    public int getTestIntList(int index) {
      return testIntList_.getInt(index);
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @param index The index to set the value at.
     * @param value The testIntList to set.
     * @return This builder for chaining.
     */
    public Builder setTestIntList(
        int index, int value) {
      ensureTestIntListIsMutable();
      testIntList_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @param value The testIntList to add.
     * @return This builder for chaining.
     */
    public Builder addTestIntList(int value) {
      ensureTestIntListIsMutable();
      testIntList_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @param values The testIntList to add.
     * @return This builder for chaining.
     */
    public Builder addAllTestIntList(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureTestIntListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, testIntList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 test_int_list = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestIntList() {
      testIntList_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.BasicTestIntMessageList)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.BasicTestIntMessageList)
  private static final org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList();
  }

  public static org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BasicTestIntMessageList>
      PARSER = new com.google.protobuf.AbstractParser<BasicTestIntMessageList>() {
    @java.lang.Override
    public BasicTestIntMessageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BasicTestIntMessageList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BasicTestIntMessageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BasicTestIntMessageList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mapstruct.ap.protobuf.test._target.BasicTestIntMessageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

